app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::group(['middleware' => ['auth']], function()
{
	Route::resource('admin/users', 'UsersController');
	Route::get('admin/taskgroups/images/{id}', 'TaskgroupsController@images');
	Route::get('admin/taskgroups/locations/{id}', 'TaskgroupsController@locations');
	Route::get('admin/taskgroups/duplicate', 'TaskgroupsController@duplicate');
	Route::post('admin/taskgroups/post_duplicate', 'TaskgroupsController@post_duplicate');
	Route::post('admin/taskgroups/status/{id}', 'TaskgroupsController@status');
	Route::resource('admin/taskgroups', 'TaskgroupsController');
	Route::resource('admin/locations', 'LocationsController');
	Route::resource('admin/tasks', 'TasksController');
	Route::resource('admin/answers', 'AnswersController');
	Route::resource('admin/registrations', 'RegistrationsController');
	Route::resource('admin/clients', 'ClientsController');
	Route::resource('admin/globalvars', 'GlobalVarsController');

	/* individual routes */
	Route::post('admin/locations/bulk', 'LocationsController@bulk_import');
	Route::get('admin/locations/results/{locations}', 'LocationsController@results');
	Route::get('admin/quality/edit/{id}/{status?}', 'QualityController@edit');
	Route::get('admin/quality', 'QualityController@index');
	Route::get('admin/quality/{id}/{status?}', 'QualityController@show');
	Route::post('admin/quality/{id}/{status?}', 'QualityController@update');

	Route::get('admin/payment/edit/{id}/{status?}', 'PaymentController@edit');
	Route::post('admin/payment/bulk/{status}', 'PaymentController@bulk');
	Route::get('admin/payment/{status?}/{group?}', 'PaymentController@index');
	Route::post('admin/payment/{id}/{status?}', 'PaymentController@update');
	

});

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
    'name', 'address', 'contact_data', 'payment_data', 'type', 'is_active',
    ];

    public static $rules = array(
        'name' => 'required|min:5',
        );

    public function taskgroups()
    {
        return $this->hasMany('App\Taskgroup');
    }

    public static function scopeActive($query)
    {   
        return $query->where('is_active', true);
    }
    

    public function getStatusTextAttribute()
    {
        return $this->attributes['is_active'] ? 'active' : 'inactive'; 
    }
}

app/Http/Controllers/ClientsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\Client;
use App\Taskgroup;
use View;
use Input;
use Validator;
use Redirect;

class ClientsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clients = Client::with('taskgroups')->get();
        return View::make('admin.clients.index', compact('clients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $client = new Client;
        return View::make('admin.clients.create', compact('client'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = Input::all();
        $input['is_active'] = isset($input['is_active']) && $input['is_active'] == 'on' ? true : false;
        $validation = Validator::make($input, Client::$rules);
        if ($validation->passes())
        {
            Client::create($input);
            return Redirect::route('admin.clients.index');
        }
        return Redirect::route('admin.clients.create')
        ->withInput()
        ->withErrors($validation);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $client = Client::with('taskgroups')->findOrFail($id);
        return View::make('admin.clients.edit', compact('client'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $client = Client::findOrFail($id);
        $input = Input::all();
        $input['is_active'] = isset($input['is_active']) && $input['is_active'] == 'on' ? true : false;
        $validation = Validator::make($input, Client::$rules);
        if ($validation->passes())
        {
            $client->update($input);
            return Redirect::route('admin.clients.index');
        }
        return Redirect::route('admin.clients.edit', [$registration])
        ->withInput()
        ->withErrors($validation);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $client = Client::find($id);
        $checktg = Taskgroup::where('client_id', $id)->first();
        if(!$checktg) {
            $client->delete();
            alert()->success('Client deleted successfully');
        } else {
            $client->update(array('is_active' => false));
            alert()->warning('Client could not be deleted', 'Made inactive instead');
        }
        return Redirect::route('admin.clients.index');
    }
}

resources/views/admin/clients/create.blade.php
@extends('layouts.app')

@section('content')
<div class="main-full-back text-center vcenter min-height-100pc pt-20">
	<div class="container">
		<div class="row">
			<div class="col-md-10 col-md-offset-1 text-left">
				<div class="panel panel-default">
					<div class="panel-heading clearfix">
						<h3 class="panel-title lh-2">Create Client
						<span class="pull-right">{{ link_to_route('admin.clients.index', 'Cancel', array(), array('class' => 'btn btn-danger dib btn-sm')) }}</span>
						</h3>
					</div>
					<div class="panel-body">
						@include('admin.partials._formClient')
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection
@push('styles')
<link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap3-wysiwyg/0.3.3/bootstrap3-wysihtml5.min.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/flick/jquery-ui.css">
<link href="https://cdnjs.cloudflare.com/ajax/libs/tag-it/2.0/css/jquery.tagit.min.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/3.3.2/css/bootstrap2/bootstrap-switch.min.css" rel="stylesheet">
@endpush
@push('scripts')
<script src='http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.24/jquery-ui.min.js'></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/wysihtml/0.4.15/wysihtml5x-toolbar.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/handlebars.js/1.3.0/handlebars.runtime.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap3-wysiwyg/0.3.3/bootstrap3-wysihtml5.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tag-it/2.0/js/tag-it.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/3.3.2/js/bootstrap-switch.min.js"></script>
<script type="text/javascript">
$('.switch').bootstrapSwitch();
</script>
<script>
$(".textarea").each(function(){$(this).wysihtml5();});
$(function(){
	$('.tagit').tagit();
});
</script>
@endpush

resources/views/admin/clients/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="main-full-back text-center vcenter min-height-100pc pt-20">
	<div class="container">
		<div class="row">
			<div class="col-md-10 col-md-offset-1 text-left">
				<div class="panel panel-default">
					<div class="panel-heading clearfix">
						<h3 class="panel-title lh-2">Edit Client
						<span class="pull-right">{{ link_to_route('admin.clients.index', 'Cancel', array(), array('class' => 'btn btn-danger dib btn-sm')) }}</span>
						</h3>
					</div>
					<div class="panel-body">
						@include('admin.partials._formClient')
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection
@push('styles')
<link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap3-wysiwyg/0.3.3/bootstrap3-wysihtml5.min.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/flick/jquery-ui.css">
<link href="https://cdnjs.cloudflare.com/ajax/libs/tag-it/2.0/css/jquery.tagit.min.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/3.3.2/css/bootstrap2/bootstrap-switch.min.css" rel="stylesheet">
@endpush
@push('scripts')
<script src='http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.24/jquery-ui.min.js'></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/wysihtml/0.4.15/wysihtml5x-toolbar.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/handlebars.js/1.3.0/handlebars.runtime.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap3-wysiwyg/0.3.3/bootstrap3-wysihtml5.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tag-it/2.0/js/tag-it.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/3.3.2/js/bootstrap-switch.min.js"></script>
<script type="text/javascript">
$('.switch').bootstrapSwitch();
</script>
<script>
$(".textarea").each(function(){$(this).wysihtml5();});
$(function(){
	$('.tagit').tagit();
});
</script>
@endpush

resources/views/admin/clients/index.blade.php
@extends('layouts.app')

@section('content')
<div class="main-full-back text-center vcenter min-height-100pc pt-20">
	<div class="container">
		<div class="row">
			<div class="col-md-10 col-md-offset-1 text-left">
				<div class="panel panel-default">
					<div class="panel-heading clearfix">
						<h3 class="panel-title lh-2">All Clients
						<span class="pull-right lh-16">{{ link_to_route('admin.clients.create', 'Add new client', array(), array('class' => 'btn btn-success dib btn-sm')) }}</span>
						</h3>
					</div>

					<div class="panel-body">
						@if ($clients->count())
						<table class="table table-striped table-condensed fs-13" id="datatable">
							<thead>
								<tr>
									<th>ID</th>
									<th>Name</th>
									<th>Address</th>
									<th>Type</th>
									<th>Status</th>
									<th>Actions</th>
								</tr>
							</thead>
							<tbody>
								@foreach ($clients as $client)
								<tr>
									<td>{{ $client->id }}</td>
									<td>{{ $client->name }}</td>
									<td>{{ $client->address }}</td>
									<td>{{ $client->type }}</td>
									<td>{{ $client->status_text }}</td>
									<td>{!! Html::decode(link_to_route('admin.clients.edit', '<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array($client->id), array('class' => 'btn btn-info dib btn-sm'))) !!}
										<span class="dib">|</span>
										{{ Form::open(array('method' => 'delete','id'=>'delete_form', 'route' => array('admin.clients.destroy', $client->id), 'class' => 'dib' )) }}
										{!! Html::decode(Form::button('<i class="fa fa-trash-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm delete-btn'))) !!}
										{{ Form::close() }}
									</td>
								</tr>
								@endforeach
							</tbody>
							<tfoot>
								<tr>
									<td></td>
									<th>Name</th>
									<th>Address</th>
									<th>Type</th>
									<th>Status</th>
									<td></td>
								</tr>
							</tfoot>
						</table>
						@else
						There are no clients
						@endif
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection
@push('styles')
<link href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="https://cdn.datatables.net/buttons/1.2.2/css/buttons.dataTables.min.css" rel="stylesheet">
@endpush
@push('scripts')
<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
<script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
<script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    // Setup - add a text input to each footer cell
    $('#datatable tfoot th').each( function () {
    	var title = $(this).text();
    	$(this).html( '<input type="text" placeholder="Search '+title+'" size="12" id="fs"  />' );
    } );

    // DataTable
    var table = $('#datatable').DataTable({
    	dom: "<'row'<'col-sm-4'l><'col-sm-4'B><'col-sm-4'f>>" +
    	"<'row'<'col-sm-12'tr>>" +
    	"<'row'<'col-sm-5'i><'col-sm-7'p>>",
    	buttons: [
    	{
    		extend: "csv",
    		exportOptions: {
    			columns: [0, 1, 2, 3, 4]
    		}
    	},
    	{
    		extend: "excel",
    		exportOptions: {
    			columns: [0, 1, 2, 3, 4]
    		}
    	},
    	{
    		extend: "pdf",
    		exportOptions: {
    			columns: [0, 1, 2, 3, 4]
    		}
    	},
    	{
    		extend: "print",
    		exportOptions: {
    			columns: [0, 1, 2, 3, 4]
    		}
    	}
    	],
    	columnDefs: [{orderable: false, targets: -1 }],
    	order: [[ 0, "desc" ]],
    	stateSave: true
    });

    // Apply the search
    table.columns().every( function () {
    	var that = this;

    	$( 'input#fs', this.footer() ).on( 'keyup change', function () {
    		if ( that.search() !== this.value ) {
    			that
    			.search( this.value )
    			.draw();
    		}
    	} );
    });

});
$('button.delete-btn').on('click', function(e){
	e.preventDefault();
	var self = $(this);
	swal({
		title             : "Are you sure?",
		text              : "This client be deleted!",
		type              : "warning",
		showCancelButton  : true,
		confirmButtonColor: "#DD6B55",
		confirmButtonText : "Yes, delete it!",
		cancelButtonText  : "No, Cancel",
		closeOnConfirm    : false,
		closeOnCancel     : false
	},
	function(isConfirm){
		if(isConfirm){
			self.parents("#delete_form").submit();
		}
		else{
			swal("Cancelled","Your Client is safe", "error");
		}
	});
});
</script>
@endpush