app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::group(['middleware' => ['auth']], function()
{
	Route::resource('admin/users', 'UsersController');
	Route::get('admin/taskgroups/images/{id}', 'TaskgroupsController@images');
	Route::get('admin/taskgroups/locations/{id}', 'TaskgroupsController@locations');
	Route::get('admin/taskgroups/duplicate', 'TaskgroupsController@duplicate');
	Route::post('admin/taskgroups/post_duplicate', 'TaskgroupsController@post_duplicate');
	Route::post('admin/taskgroups/status/{id}', 'TaskgroupsController@status');
	Route::resource('admin/taskgroups', 'TaskgroupsController');
	Route::resource('admin/locations', 'LocationsController');
	Route::resource('admin/tasks', 'TasksController');
	Route::resource('admin/answers', 'AnswersController');
	Route::resource('admin/registrations', 'RegistrationsController');
	Route::resource('admin/clients', 'ClientsController');
	Route::resource('admin/globalvars', 'GlobalVarsController');

	/* individual routes */
	Route::post('admin/locations/bulk', 'LocationsController@bulk_import');
	Route::get('admin/locations/results/{locations}', 'LocationsController@results');
	Route::get('admin/quality/edit/{id}/{status?}', 'QualityController@edit');
	Route::get('admin/quality', 'QualityController@index');
	Route::get('admin/quality/{id}/{status?}', 'QualityController@show');
	Route::post('admin/quality/{id}/{status?}', 'QualityController@update');

	Route::get('admin/payment/edit/{id}/{status?}', 'PaymentController@edit');
	Route::post('admin/payment/bulk/{status}', 'PaymentController@bulk');
	Route::get('admin/payment/{status?}/{group?}', 'PaymentController@index');
	Route::post('admin/payment/{id}/{status?}', 'PaymentController@update');
	

});

app/Taskgroup.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use Carbon;

class Taskgroup extends Model
{
	protected $fillable = [
	'name', 'short_description', 'long_description', 'start_date', 'end_date', 'image', 'max_users', 'pin_color', 'media_url', 'client_id', 'is_active', 'commission_date', 'delivery_date', 'settlement_date', 'action_date',
	];


	public static $rules = array(
		'name' => 'required|min:3',
		'short_description' => 'required|min:3',
		'long_description' => 'required|min:3',
		'start_date' => 'required|date',
		'end_date' => 'required|date|after:start_date',
		'client_id' => 'required',
		'image'=>'mimes:jpg,jpeg,png|max:500',
		);

	private $media_types = [
     'image' => 'Image',
     'link' => 'Link',
     'pdf' => 'PDF',
     ];

	public function locations()
    {
        return $this->belongsToMany('App\Location')->withPivot('is_active');
    }

    public function active_locations()
    {
        return $this->belongsToMany('App\Location')->wherePivot('is_active', 1);
    }

    public function tasks()
    {
        return $this->hasMany('App\Task');
    }


    public function clients()
    {
        return $this->belongsTo('App\Client');
    }

    public function scopeMediaTypes() {
        return $this->media_types;
    }

    public function getStatusTextAttribute()
    {
        if(!$this->attributes['is_active'] && $this->attributes['action_date']<$this->attributes['start_date']) : $status = 'draft';
        elseif($this->attributes['is_active'] && date("Y-m-d h:i:s")<$this->attributes['start_date']) : $status = 'pending';  $status = 'draft';
        elseif($this->attributes['is_active'] && $this->attributes['start_date']<=date("Y-m-d h:i:s") && date("Y-m-d h:i:s")<=$this->attributes['end_date']) : $status = 'live';
        elseif(!$this->attributes['is_active'] && $this->attributes['start_date']<$this->attributes['action_date'] && $this->attributes['action_date']<$this->attributes['end_date']) : $status = 'paused';
        elseif($this->attributes['is_active'] && $this->attributes['end_date']<date("Y-m-d h:i:s")) : $status = 'ended';
        elseif(!$this->attributes['is_active'] && $this->attributes['end_date']<$this->attributes['action_date']) : $status = 'completed';
        endif;
        return $status; 
    }

    public function getStartDateParseAttribute()
    {
        return Carbon::parse($this->attributes['start_date']); 
    }

    public function getEndDateParseAttribute()
    {
        return Carbon::parse($this->attributes['end_date']); 
    }

    public function getCommissionDateParseAttribute()
    {
        return Carbon::parse($this->attributes['commission_date']); 
    }

    public function getDeliveryDateParseAttribute()
    {
        return Carbon::parse($this->attributes['delivery_date']); 
    }

    public function getSettlementDateParseAttribute()
    {
        return Carbon::parse($this->attributes['settlement_date']); 
    }

    public static function sortArray($data, $field)
	{
		if(!is_array($field)) $field = array($field);
		usort($data, function($a, $b) use($field) {
			$retval = 0;
			foreach($field as $fieldname) {
				if($retval == 0) $retval = strnatcmp($a[$fieldname],$b[$fieldname]);
			}
			return $retval;
		});
		return $data;
	}
}

app/Http/Controllers/TaskgroupsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\Taskgroup;
use App\Task;
use App\Answer;
use App\Location;
use App\Client;
use App\Registration;
use View;
use Carbon;
use DB;
use Input;
use Validator;
use Redirect;

class TaskgroupsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $taskgroups = Taskgroup::all();
        $statuses = array(''=>'all', 'draft'=>'draft','pending'=>'pending','live'=>'live','paused'=>'paused','ended'=>'ended','completed'=>'completed');
        return View::make('admin.taskgroups.index', compact('taskgroups','statuses'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $taskgroup = new Taskgroup;
        $now = strtotime(date("Y-m-d 00:00"));
        $taskgroup->start_date = date('Y-m-d 00:00', strtotime("+1 day", $now));
        $taskgroup->end_date = date('Y-m-d 00:00', strtotime("+5 days", $now));
        $taskgroup->commission_date = date('Y-m-d 00:00', strtotime("+5 days", $now));
        $taskgroup->delivery_date = date('Y-m-d 00:00', strtotime("+5 days", $now));
        $taskgroup->settlement_date = date('Y-m-d 00:00', strtotime("+5 days", $now));
        $taskgroup['orderby'] = array_combine(range(1,10),range(1,10));
        $taskgroup['statuses'] = array_combine(range(0,1),array('inactive','active'));
        $taskgroup['media_types'] = Taskgroup::mediaTypes();
        $clients = [''=> 'Please select'] + Client::active()->lists('name','id')->toArray();
        $taskgroup['available'] = $request->old('available') ? Location::activeValid($request->old('available'))->lists('name_tags','id') : Location::activeValid()->lists('name_tags','id');
        $taskgroup['locations'] = $request->old('locations') ? Location::activeValid($request->old('locations'))->lists('name_tags','id') : array();
        return View::make('admin.taskgroups.create', compact('taskgroup', 'clients'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = Input::all();
        unset($input['available']);
        if(!empty(array_values($input['media_url'])[0]['title'])){
            $media_url = Taskgroup::sortArray($input['media_url'], 'order');
            $input['media_url'] = json_encode(array('media' => $media_url));
        } else {
            unset($input['media_url']);
        }
        //$input['is_active'] = isset($input['is_active']) && $input['is_active'] == 'on' ? 1 : 0;
        $messages = ['between' => 'The :attribute must be between :min - :max.'];
        $validation = Validator::make($input, array_merge(Taskgroup::$rules, array('image'=>'required', 'locations'=>'required|between:1,'.$input['max_users'])), $messages);
        if ($validation->passes())
        {
            $locs = isset($input['locations']) ? $input['locations'] : null; unset($input['locations']);
            $filename = uniqid('taskgroup_',false).'_'.time().'.'.$request->file('image')->getClientOriginalExtension();
            $request->file('image')->move(
                base_path() . '/public/images/taskgroups/', $filename
                );
            $input['image'] = $filename;
            $taskgroup = Taskgroup::create($input);
            $taskgroup->locations()->attach($locs);
            return Redirect::route('admin.taskgroups.index');
        }
        return Redirect::route('admin.taskgroups.create')
        ->withInput()
        ->withErrors($validation);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        $taskgroup = Taskgroup::with('active_locations')->findOrFail($id);
        $taskgroup['media_url'] = json_decode($taskgroup['media_url']);
        $taskgroup['locations'] = $taskgroup->active_locations->pluck('id')->toArray();
        $taskgroup['orderby'] = array_combine(range(1,10),range(1,10));
        $taskgroup['statuses'] = array_combine(range(0,1),array('inactive','active'));
        $taskgroup['media_types'] = Taskgroup::mediaTypes();
        $clients = [''=> 'Please select'] + Client::active()->lists('name','id')->toArray();
        $all_locations = Location::activeValid()->lists('name_tags','id')->toArray();
        $taskgroup['available'] = $request->old('available') ? Location::activeValid($request->old('available'))->lists('name_tags','id') : Location::ActiveValidNot($taskgroup['locations'])->lists('name_tags','id');
        $taskgroup['locations'] = $request->old('locations') ? Location::activeValid($request->old('locations'))->lists('name_tags','id') : Location::ActiveValid($taskgroup['locations'])->lists('name_tags','id');
        $status = [];
        if(!$taskgroup['is_active'] && $taskgroup['action_date']<$taskgroup['start_date']) : $status['state'] = 'draft'; $status['action'] = 'activate'; $status['btn'] = 'success';
        elseif($taskgroup['is_active'] && date("Y-m-d h:i:s")<$taskgroup['start_date']) : $status['state'] = 'pending';  $status['action'] = 'draft'; $status['btn'] = 'primary';
        elseif($taskgroup['is_active'] && $taskgroup['start_date']<=date("Y-m-d h:i:s") && date("Y-m-d h:i:s")<=$taskgroup['end_date']) : $status['state'] = 'live';  $status['action'] = 'pause'; $status['btn'] = 'warning'; 
        elseif(!$taskgroup['is_active'] && $taskgroup['start_date']<$taskgroup['action_date'] && $taskgroup['action_date']<$taskgroup['end_date']) : $status['state'] = 'paused'; $status['action'] = 'resume'; $status['btn'] = 'success';
        elseif($taskgroup['is_active'] && $taskgroup['end_date']<date("Y-m-d h:i:s")) : $status['state'] = 'ended';  $status['action'] = 'complete'; $status['btn'] = 'info';
        elseif(!$taskgroup['is_active'] && $taskgroup['end_date']<$taskgroup['action_date']) : $status['state'] = 'completed'; $status['action'] = ''; $status['btn'] = '';
        endif;
        return View::make('admin.taskgroups.edit', compact('taskgroup', 'clients', 'status'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $taskgroup = Taskgroup::with('locations')->findOrFail($id);
        $input = Input::all();
        unset($input['available']);
        if(!empty(array_values($input['media_url'])[0]['title'])){
            $media_url = Taskgroup::sortArray($input['media_url'], 'order');
            $input['media_url'] = json_encode(array('media' => $media_url));
        } else {
            unset($input['media_url']);
        }
        $messages = ['between' => 'The :attribute must be between :min - :max.'];
        $validation = Validator::make($input, array_merge(Taskgroup::$rules, array('locations'=>'required|between:1,'.$input['max_users'])), $messages);
        if ($validation->passes())
        {
            $locations = isset($input['locations']) ? $input['locations'] : null; unset($input['locations']);
            if(isset($input['image'])) {
                if(file_exists(base_path()."images/taskgroups/".$taskgroup->photo)) unlink(base_path()."images/taskgroups/".$taskgroup->photo);
                $filename = uniqid('taskgroup_',false).'_'.time().'.'.$request->file('image')->getClientOriginalExtension();
                $request->file('image')->move(
                    base_path() . '/public/images/taskgroups/', $filename
                    );
                $input['image'] = $filename;
            }
            $locations = array_flip($locations);
            foreach ($locations as $key => $value) {
                $locations[$key] = array('is_active'=>true);
            }
            foreach ($taskgroup->locations as $loc) {
                if (!array_key_exists($loc->id, $locations)) {
                    $checkreg = Registration::where('location_id', $loc->id)->where('taskgroup_id', $taskgroup->id)->first();
                    if(!$checkreg) {
                        DB::table('location_taskgroup')->where('location_id', $loc->id)->where('taskgroup_id', $taskgroup->id)->delete();
                    } else {
                        $locations[$loc->id] = array('is_active'=>false);
                    }
                }
            }
            $taskgroup->update($input);
            $taskgroup->locations()->sync($locations);
            return Redirect::route('admin.taskgroups.index');
        }
        return Redirect::route('admin.taskgroups.edit', [$taskgroup])
        ->withInput()
        ->withErrors($validation);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $taskgroup = Taskgroup::find($id);
        $checkreg = Registration::where('taskgroup_id', $id)->first();
        if(!$checkreg) {
            Task::where('taskgroup_id', $taskgroup->id)->delete();
            DB::table('location_taskgroup')->where('taskgroup_id', $taskgroup->id)->delete();
            if(file_exists(base_path()."images/taskgroups/".$taskgroup->photo)) unlink(base_path()."images/taskgroups/".$taskgroup->photo);
            $taskgroup->delete();
            alert()->success('Taskgroup deleted successfully');
        } else {
            $taskgroup->update(array('is_active' => false));

resources/views/admin/taskgroups/create.blade.php
@extends('layouts.app')

@section('content')
<div class="main-full-back text-center vcenter min-height-100pc pt-20">
	<div class="container">
		<div class="row">
			<div class="col-md-10 col-md-offset-1 text-left">
				<div class="panel panel-default">
					<div class="panel-heading clearfix">
						<h3 class="panel-title lh-2">Create Project
                        <span class="pull-right">{{ link_to_route('admin.taskgroups.index', 'Cancel', array(), array('class' => 'btn btn-danger dib btn-sm')) }}</span>
                        </h3>
					</div>
					<div class="panel-body">
						@include('admin.partials._formTaskgroup')
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection
@push('styles')
<link href="//cdnjs.cloudflare.com/ajax/libs/chosen/1.6.2/chosen.min.css" rel="stylesheet">
<link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap3-wysiwyg/0.3.3/bootstrap3-wysihtml5.min.css" rel="stylesheet">
<link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.43/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
<link href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css" rel="stylesheet">
<link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/3.3.2/css/bootstrap2/bootstrap-switch.min.css" rel="stylesheet">
@endpush
@push('scripts')
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-filestyle/1.2.1/bootstrap-filestyle.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/wysihtml/0.4.15/wysihtml5x-toolbar.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/handlebars.js/1.3.0/handlebars.runtime.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap3-wysiwyg/0.3.3/bootstrap3-wysihtml5.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.0/moment.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.43/js/bootstrap-datetimepicker.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/3.3.2/js/bootstrap-switch.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/chosen/1.6.2/chosen.jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/multiselect/2.2.9/js/multiselect.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jscolor/2.0.4/jscolor.min.js"></script>
<script>
$(".textarea").each(function(){$(this).wysihtml5();});
$('.switch').bootstrapSwitch();
$('.chosen').chosen();
$('#multiselect').multiselect({
    search: {
        left: '<input type="text" name="q" class="form-control" placeholder="Search..." />',
    }
});
$("#start_date").datetimepicker({
    defaultDate: "{!! $taskgroup->start_date_parse->format('Y-m-d H:i') !!}",
    format:'YYYY-MM-DD HH:mm'
});
$("#end_date").datetimepicker({
    defaultDate: "{!! $taskgroup->end_date_parse->format('Y-m-d H:i') !!}",
    format:'YYYY-MM-DD HH:mm'
});
$("#commission_date").datetimepicker({
    defaultDate: "{!! $taskgroup->commission_date_parse->format('Y-m-d H:i') !!}",
    format:'YYYY-MM-DD HH:mm'
});
$("#delivery_date").datetimepicker({
    defaultDate: "{!! $taskgroup->delivery_date_parse->format('Y-m-d H:i') !!}",
    format:'YYYY-MM-DD HH:mm'
});
$("#settlement_date").datetimepicker({
    defaultDate: "{!! $taskgroup->settlement_date_parse->format('Y-m-d H:i') !!}",
    format:'YYYY-MM-DD HH:mm'
});
$(function () {
    $(":file").filestyle();
});
$(document).ready(function() {
    $('#multiselect').multiselect();
    
    var max_fields      = 10; //maximum input boxes allowed
    var wrapper         = $(".input_fields_wrap"); //Fields wrapper
    var add_button      = $(".add_field_button"); //Add button ID
    
    
    var x = 1; //initlal text box count
    $(add_button).click(function(e){ //on add input button click
        e.preventDefault();
        var rand = Math.floor(Math.random() * 10000000000);
        if(x < max_fields){ //max input box allowed
            x++; //text box increment
            $(wrapper).append('<div class="row mb-10">'+
                '<div class="col-md-3"><input autocomplete="off" required="1" class="form-control" name="media_url['+rand+'][title]" placeholder="Media title" type="text"/></div>'+
                '<div class="col-md-3"><input autocomplete="off" required="1" class="form-control" name="media_url['+rand+'][url]" type="text" placeholder="Media URL" /></div>'+
                '<div class="col-md-2"><select autocomplete="off" required="1" class="form-control" id="type'+rand+'" name="media_url['+rand+'][type]"></select></div>'+
                '<div class="col-md-2"><select autocomplete="off" required="1" class="form-control" id="order'+rand+'" name="media_url['+rand+'][order]"></select></div>'+
                '<div class="col-md-2"><input autocomplete="off" required="1" name="media_url['+rand+'][is_active]" type="hidden" value="1" /><a href="#" class="remove_field input-group-addon">Remove</a></div>');
            //add input box
            var ts = document.getElementById('type'+rand);
            nots = document.createElement('option'); nots.innerHTML = 'Media Type'; ts.appendChild(nots);
            imgts = document.createElement('option'); imgts.value = 'image'; imgts.innerHTML = 'Image'; ts.appendChild(imgts);
            lnkts = document.createElement('option'); lnkts.value = 'link'; lnkts.innerHTML = 'Link'; ts.appendChild(lnkts);
            pdfts = document.createElement('option'); pdfts.value = 'pdf'; pdfts.innerHTML = 'PDF'; ts.appendChild(pdfts);

            var os = document.getElementById('order'+rand);
            noos = document.createElement('option'); noos.innerHTML = 'Media Order'; os.appendChild(noos);
            for (i = 1; i < 10; i++) {
                var osopt = document.createElement('option');
                osopt.value = i;
                osopt.innerHTML = i;
                os.appendChild(osopt);
            }

        }
    });

    $(wrapper).on("click",".remove_field", function(e){ //user click on remove text
        e.preventDefault(); $(this).parent('div').parent('div').remove(); x--;
    })
});
</script>
@endpush

resources/views/admin/taskgroups/duplicate.blade.php
@extends('layouts.app')

@section('content')
<div class="main-full-back text-center vcenter min-height-100pc pt-20">
	<div class="container">
		<div class="row">
			<div class="col-md-10 col-md-offset-1 text-left">
				<div class="panel panel-default">
					<div class="panel-heading clearfix">
						<h3 class="panel-title lh-2">Select Project</h3>
					</div>
					
					<div class="panel-body form-group clearfix">
						{!! BootForm::open(['action' => 'TaskgroupsController@post_duplicate', 'method' => 'post', 'class' => 'duplicate_form']) !!}
						{!! BootForm::select('taskgroup', 'Project', $taskgroups, null, ['required' => true, 'autocomplete' => 'off', 'class' => 'form-control']) !!}
						{!! BootForm::submit('Submit',  ['class' => 'duplicate-btn btn btn-primary pull-right text-white pull-right' ]) !!}
						{{ BootForm::close() }}
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection
@push('scripts')
<script type="text/javascript">
$('.duplicate-btn').on('click', function(e){
	e.preventDefault();
	var self = $(this);
	swal({
		title             : "Are you sure?",
		text              : "This Project will be duplicated!",
		type              : "info",
		showCancelButton  : true,
		confirmButtonColor: "#5bc0de",
		confirmButtonText : "Yes, duplicated it!",
		cancelButtonText  : "No, Cancel",
		closeOnConfirm    : false,
		closeOnCancel     : false
	},
	function(isConfirm){
		if(isConfirm){
			self.parents(".duplicate_form").submit();
		}
		else{
			swal("Cancelled","Your Project is not duplicated", "error");
		}
	});
});
</script>
@endpush

resources/views/admin/taskgroups/images.blade.php
@extends('layouts.app')

@section('content')
<div class="main-full-back text-center vcenter min-height-100pc pt-20">
	<div class="container">
		<div class="row">
			<div class="col-md-10 col-md-offset-1 text-left">
				<div class="panel panel-default">
					<div class="panel-heading clearfix">
						<h3 class="panel-title lh-16">
							Images {{Html::linkAction('TaskgroupsController@index', 'Cancel', null, array('class' => 'btn btn-danger dib btn-sm pull-right text-white'))}}
						</h3>
					</div>
					<div class="panel-body">
						<h5 class="mt-0">Project: {{ $taskgroup->name }}</h5>
						
					</div>
				</div>
				
				@if ($tasks->count())
				@foreach ($tasks as $task)
				<div class="panel panel-default mb-20">
					<div class="panel-heading clearfix">
						<h5 class="mt-0 mb-0 lh-2 col-md-5 pl-0">Question: {{$task['description']->question}}</h5>
					</div>
					<div class="panel-body row ml-0 mr-0">
						@if ($task->answers->count())
						@foreach ($task->answers as $answer)
						<div class="col-md-3 panel panel-default text-center">
							<div class="panel-body pl-0 pr-0 pb-0">{{ Html::image('images/answers/'.$answer['data'], $task['description']->question, array('class' => 'img-responsive')) }}</div>
							<div class="panel-footer mb-10 pl-5 pr-5 fs-13">
								<strong>User</strong>: {{ Helper::getProfileFromAnswer($answer['user_id'])['name'] }} {{ Helper::getProfileFromAnswer($answer['user_id'])['surname'] }}<br />
								<strong>Address</strong>: {{ Helper::getLocationFromRegistration($answer['registration_id'])['name'] }} ({{ Helper::getLocationFromRegistration($answer['registration_id'])['address'] }})<br />
								@if($answer['created_at'])<strong>Time</strong>: {{ $answer['created_at']->format('m/d/Y H:i') }}@endif
							</div>
						</div>
						@endforeach
						@else
						There are no multimedia files uploaded yet
						@endif
					</div>
				</div>
				@endforeach
				@else
				<div class="panel panel-default mb-20">
					<div class="panel-heading clearfix">
						<h5 class="mt-0 mb-0 lh-2 col-md-5 pl-0">There are no multimedia jobs</h5>
					</div>
				</div>	
				@endif
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/admin/taskgroups/locations.blade.php
@extends('layouts.app')

@section('content')
<div class="main-full-back text-center vcenter min-height-100pc pt-20">
	<div class="container">
		<div class="row">
			<div class="col-md-10 col-md-offset-1 text-left">
				<div class="panel panel-default">
					<div class="panel-heading clearfix">
						<h3 class="panel-title lh-16">
							Activity: {{ $taskgroup->name }} {{Html::linkAction('TaskgroupsController@index', 'Cancel', null, array('class' => 'btn btn-danger dib btn-sm pull-right text-white'))}}
						</h3>
					</div>
					<div class="panel-body">
						@if ($taskgroup->active_locations->count())
						<table class="table table-striped table-condensed fs-13" id="datatable" style="width:100%;">
							<thead>
								<tr>
									<th>Name</th>
									<th>Address</th>
									<th>Status</th>
									<th>User</th>
									<th>Time</th>
								</tr>
							</thead>
							<tbody>
								@foreach ($taskgroup->active_locations as $location)
								<tr>
									<td>{{ $location->name }}</td>
									<td>{{ $location->adddress }}</td>
									<td>@if ($location->reg_status) {{ Helper::getRegistrationStatusById($location->reg_status) }} @else - @endif</td>
									<td>@if ($location->reg_user) {{ Helper::getUser($location->reg_user) }} @else - @endif</td>
									<td>@if ($location->reg_time) {{ $location->reg_time->format('m/d/Y H:i') }} @else - @endif</td>
								</tr>
								@endforeach
							</tbody>
						</table>
						@else
						There is no activity
						@endif
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection