app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::group(['middleware' => ['auth']], function()
{
	Route::resource('admin/users', 'UsersController');
	Route::get('admin/taskgroups/images/{id}', 'TaskgroupsController@images');
	Route::get('admin/taskgroups/locations/{id}', 'TaskgroupsController@locations');
	Route::get('admin/taskgroups/duplicate', 'TaskgroupsController@duplicate');
	Route::post('admin/taskgroups/post_duplicate', 'TaskgroupsController@post_duplicate');
	Route::post('admin/taskgroups/status/{id}', 'TaskgroupsController@status');
	Route::resource('admin/taskgroups', 'TaskgroupsController');
	Route::resource('admin/locations', 'LocationsController');
	Route::resource('admin/tasks', 'TasksController');
	Route::resource('admin/answers', 'AnswersController');
	Route::resource('admin/registrations', 'RegistrationsController');
	Route::resource('admin/clients', 'ClientsController');
	Route::resource('admin/globalvars', 'GlobalVarsController');

	/* individual routes */
	Route::post('admin/locations/bulk', 'LocationsController@bulk_import');
	Route::get('admin/locations/results/{locations}', 'LocationsController@results');
	Route::get('admin/quality/edit/{id}/{status?}', 'QualityController@edit');
	Route::get('admin/quality', 'QualityController@index');
	Route::get('admin/quality/{id}/{status?}', 'QualityController@show');
	Route::post('admin/quality/{id}/{status?}', 'QualityController@update');

	Route::get('admin/payment/edit/{id}/{status?}', 'PaymentController@edit');
	Route::post('admin/payment/bulk/{status}', 'PaymentController@bulk');
	Route::get('admin/payment/{status?}/{group?}', 'PaymentController@index');
	Route::post('admin/payment/{id}/{status?}', 'PaymentController@update');
	

});

app/GlobalVar.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class GlobalVar extends Model
{
	/**
     * The attributes that are mass assignable.
     *
     * @var array
     */
	protected $fillable = [
	'value',
	];

	public static $rules = array(
		'max_arrival_time' => 'required',
		'max_completion_time' => 'required',
		'max_extra_time' => 'required',
		'radius' => 'required',
		'terms_link' => 'required',
	);
}

app/Http/Controllers/GlobalVarsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\GlobalVar;
use View;
use Input;
use Validator;
use Redirect;

class GlobalVarsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $globalvars = GlobalVar::get()->lists('value', 'key');
        return View::make('admin.globalvars.index', compact('globalvars'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = Input::all();
        $validation = Validator::make($input, GlobalVar::$rules);
        if ($validation->passes())
        {
            unset($input['_token']);
            foreach ($input as $key => $value) {
               $globalvar = GlobalVar::where('key', $key)->first();
               $globalvar->update(array('value'=>$value));
            }
            return Redirect::route('admin.globalvars.index');
        }
        return Redirect::route('admin.globalvars.index', [$input])
        ->withInput()
        ->withErrors($validation);
    }
}

resources/views/admin/globalvars/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="main-full-back text-center vcenter min-height-100pc pt-20">
	<div class="container">
		<div class="row">
			<div class="col-md-10 col-md-offset-1 text-left">
				<div class="panel panel-default">
					<div class="panel-heading clearfix">
						<h3 class="panel-title lh-16">Edit Answer <a href="{{ URL::route('admin.answers.index') }}" class="btn btn-danger pull-right text-white">Cancel</a></h3>
					</div>
                    <div class="panel-body">
                        <h5 class="mt-0">Project: {{ Helper::getTaskGroup($answers[0]['taskgroup_id']) }}</h5>
                        <h5 class="mt-0 mb-0">User: {{ Helper::getUser($answers[0]['user_id']) }}</h5>
                    </div>
                </div>
                @if ($answers)
                {!! BootForm::open(['action' => 'AnswersController@store']) !!}
                @foreach ($answers as $answer)
                <div class="panel panel-default mb-20">
                    <div class="panel-heading clearfix">
                        <h5 class="mt-0 mb-0 lh-16">Question: {{$answer['description']->question}}
                            <span class="btn btn-info btn-sm pull-right text-white">Money: {{$answer['money']}}</span></h5>
                        </div>
                        <div class="panel-body">
                            @if($answer['tasktype_id']==4)
                            {!! BootForm::textarea(null, 'Answer', $answer['data'], ['readonly' => true, 'rows' => 3, ]) !!}
                            @elseif ($answer['tasktype_id']==6)
                            @php $coord = explode(",",substr($answer['data'], 1, -1));@endphp
                            {!! BootForm::text(null, 'Latitude', $coord[0], ['readonly' => true ]) !!}
                            {!! BootForm::text(null, 'Longnitude', $coord[1], ['readonly' => true ]) !!}
                            @elseif ($answer['tasktype_id']==1)
                            @php $answer['data'] =  intval($answer['data']); @endphp
                            {!! BootForm::radios(null, 'Answers', $answer['description']->answers, $answer['data'], ['disabled' => true ]) !!}
                            @elseif ($answer['tasktype_id']==2)
                            @php $answer['data'] =  explode(',',$answer['data']); @endphp
                            {!! BootForm::checkboxes(null, 'Answers', $answer['description']->answers, $answer['data'], ['disabled' => true ]) !!}
                            @endif
                        </div>
                        <div class="panel-footer">
                            {!! BootForm::select('answer_status_id['.$answer["id"].']', 'Answer Status', $answer_statuses, $answer['answer_status_id'], ['required' => true]) !!}
                        </div>
                    </div>
                    @endforeach
                    <div class="panel panel-default">
                        <div class="panel-body">
                            {!! BootForm::submit('Submit',  ['class' => 'btn btn-primary pull-right text-white pull-right' ]) !!}
                        </div>
                    </div>
                    {!! BootForm::close() !!}
                    @else
                    There are no answers
                    @endif
                </div>
            </div>
        </div>
    </div>
    @endsection
    @push('scripts')
    <script type="text/javascript">
    $(':radio,:checkbox').click(function(){
        return false;
    });
    </script>
    @endpush

resources/views/admin/globalvars/index.blade.php
@extends('layouts.app')

@section('content')
<div class="main-full-back text-center vcenter min-height-100pc pt-20">
	<div class="container">
		<div class="row">
			<div class="col-md-10 col-md-offset-1 text-left">
				<div class="panel panel-default">
					<div class="panel-heading clearfix">
						<h3 class="panel-title lh-16">Edit Global Vars</h3>
					</div>
					<div class="panel-body">
						@include('admin.partials._formGlobalVars')
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection
@push('styles')
<link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap3-wysiwyg/0.3.3/bootstrap3-wysihtml5.min.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/flick/jquery-ui.css">
<link href="https://cdnjs.cloudflare.com/ajax/libs/tag-it/2.0/css/jquery.tagit.min.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/3.3.2/css/bootstrap2/bootstrap-switch.min.css" rel="stylesheet">
@endpush
@push('scripts')
<script src='http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.24/jquery-ui.min.js'></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/wysihtml/0.4.15/wysihtml5x-toolbar.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/handlebars.js/1.3.0/handlebars.runtime.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap3-wysiwyg/0.3.3/bootstrap3-wysihtml5.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tag-it/2.0/js/tag-it.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/3.3.2/js/bootstrap-switch.min.js"></script>
<script type="text/javascript">
$('.switch').bootstrapSwitch();
</script>
<script>
$(".textarea").each(function(){$(this).wysihtml5();});
$(function(){
	$('.tagit').tagit();
});
</script>
@endpush