app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::group(['middleware' => ['auth']], function()
{
	Route::resource('admin/users', 'UsersController');
	Route::get('admin/taskgroups/images/{id}', 'TaskgroupsController@images');
	Route::get('admin/taskgroups/locations/{id}', 'TaskgroupsController@locations');
	Route::get('admin/taskgroups/duplicate', 'TaskgroupsController@duplicate');
	Route::post('admin/taskgroups/post_duplicate', 'TaskgroupsController@post_duplicate');
	Route::post('admin/taskgroups/status/{id}', 'TaskgroupsController@status');
	Route::resource('admin/taskgroups', 'TaskgroupsController');
	Route::resource('admin/locations', 'LocationsController');
	Route::resource('admin/tasks', 'TasksController');
	Route::resource('admin/answers', 'AnswersController');
	Route::resource('admin/registrations', 'RegistrationsController');
	Route::resource('admin/clients', 'ClientsController');
	Route::resource('admin/globalvars', 'GlobalVarsController');

	/* individual routes */
	Route::post('admin/locations/bulk', 'LocationsController@bulk_import');
	Route::get('admin/locations/results/{locations}', 'LocationsController@results');
	Route::get('admin/quality/edit/{id}/{status?}', 'QualityController@edit');
	Route::get('admin/quality', 'QualityController@index');
	Route::get('admin/quality/{id}/{status?}', 'QualityController@show');
	Route::post('admin/quality/{id}/{status?}', 'QualityController@update');

	Route::get('admin/payment/edit/{id}/{status?}', 'PaymentController@edit');
	Route::post('admin/payment/bulk/{status}', 'PaymentController@bulk');
	Route::get('admin/payment/{status?}/{group?}', 'PaymentController@index');
	Route::post('admin/payment/{id}/{status?}', 'PaymentController@update');
	

});

app/Registration.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use DB;

class Registration extends Model
{
	protected $fillable = [
		'registration_status_id',
	];


	public static $rules = array(
		'registration_status_id'=>'required',
		);

	
	public function user()
    {
        return $this->hasOne('App\User', 'id', 'user_id');
    }

    public function location()
    {
        return $this->hasOne('App\Location', 'id', 'location_id');
    }

    public function taskgroup()
    {
        return $this->hasOne('App\Taskgroup', 'id', 'taskgroup_id');
    }

    public function profile()
    {
        return $this->hasOne('App\Profile', 'user_id', 'user_id');
    }

    public function answers()
    {
        return $this->hasMany('App\Answer');
    }

    public function scopeForQualityProccess($query, $status_ids) {
        return $query->select(DB::raw('registrations.*, GROUP_CONCAT(answers.answer_status_id ORDER BY answers.answer_status_id DESC) as answer_statuses'))->leftjoin('answers', 'answers.registration_id', '=', 'registrations.id')->whereBetween('registration_status_id', [10, 20])->whereIn('answer_status_id', $status_ids)->groupBy('answers.registration_id');
    }

    public function scopeForPaymentProccess($query, $status_ids) {
        return $query->select(DB::raw('registrations.*, MIN(answers.answer_status_id) as answers_status, SUM(tasks.money) as answers_money'))->leftjoin('answers', 'answers.registration_id', '=', 'registrations.id')->leftjoin('tasks', 'answers.task_id', '=', 'tasks.id')->whereBetween('registration_status_id', [10, 20])->whereIn('answer_status_id', $status_ids)->groupBy('answers.registration_id');
    }

    public function scopeForPaymentProccessGroup($query, $status_ids) {
        return $query->select(DB::raw('MAX(registrations.id) as id, registrations.user_id, registrations.redeem, GROUP_CONCAT(answers.id) as answers, MIN(answers.answer_status_id) as answers_status, SUM(tasks.money) as answers_money '))->leftjoin('answers', 'answers.registration_id', '=', 'registrations.id')->leftjoin('tasks', 'answers.task_id', '=', 'tasks.id')->whereBetween('registration_status_id', [10, 20])->whereIn('answer_status_id', $status_ids)->groupBy('registrations.user_id')->groupBy('registrations.redeem');
    }

    public function getRedeemStatusAttribute()
    {
        return $this->attributes['redeem'] ? 'Yes' : 'No'; 
    }
}

app/Http/Controllers/PaymentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\Registration;
use App\Task;
use App\Answer;
use View;
use DB;
use Input;
use Validator;
use Redirect;

class PaymentController extends Controller
{
	public function index($status=null, $group=null)
	{
		$statuses = DB::table('answer_statuses')->whereIn('id', [11,12,13])->get();
		$status_ids = $status ? DB::table('answer_statuses')->where('status', $status)->pluck('id') : [11,12,13];
		if($group) {
			$registrations = Registration::forPaymentProccessGroup($status_ids)->with('taskgroup')->with('location')->with('user')->get();
		} else {
			$registrations = Registration::forPaymentProccess($status_ids)->with('taskgroup')->with('location')->with('user')->get();
		}
		foreach ($registrations as $registration) {
			$registration_status = DB::table('answer_statuses')->where('id', $registration->answers_status)->value('status');
			$registration->answers_status = $registration_status;
		}
		return View::make('admin.payment.index', compact('registrations', 'status', 'group', 'statuses'));
	}

	public function edit($id, $status=null)
	{
		$status_ids = $status ? DB::table('answer_statuses')->where('status', $status)->pluck('id') : [11,12,13];
		$registration = Registration::with(['answers' => function ($query) use ($status_ids) {
			$query->whereIn('answer_status_id', $status_ids);
		}])->with('taskgroup')->with('location')->with('user')->with('profile')->findOrFail($id);
		foreach ($registration->answers as $answer) {
			$task = Task::where('id', $answer->task_id)->first();
			$answer->money = $task['money'];
			$answer_money[] = $task['money'];
			$task['description'] = json_decode($task['description']);
			$answer->description = $task['description'];
			$answer_statuses[] = $answer->answer_status_id;
		}
		$registration->total_money = array_sum($answer_money);
		$registration->answer_status = min($answer_statuses);
		$statuses = [''=> 'Please select'] + DB::table('answer_statuses')->where('id', [$registration->answer_status+1])->lists('status','id');
		return View::make('admin.payment.edit', compact('registration', 'status', 'statuses'));
	}

	public function update(Request $request, $id, $status=null)
	{
		$input = Input::all();
		foreach ($input['answer_status_id'] as $key => $value) {
			$answer = Answer::findOrFail($key);
			$update = array('answer_status_id'=>$input['status']);
			$answer->update($update);
		}
		return Redirect::action('PaymentController@index', [$status]);
	}

	public function bulk(Request $request, $status)
	{
		$input = Input::all();
		$status_id  = DB::table('answer_statuses')->where('status', $status)->pluck('id');
		if($input['user_id']) {
			$new_status = $status_id[0]+1;
			foreach ($input['user_id'] as $user_id) {
				$registrations = Registration::forPaymentProccessGroup($status_id)->where('answers.user_id', $user_id)->first();
				$answer_ids = explode(',', $registrations->answers);
				foreach ($answer_ids as $answer_id) {
					$answer = Answer::findOrFail($answer_id);
					$update = array('answer_status_id'=>$new_status);
					$answer->update($update);
				}
			}
		}
		return Redirect::action('PaymentController@index', [$status]);
	}
}

resources/views/admin/payment/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="main-full-back text-center vcenter min-height-100pc pt-20">
	<div class="container">
		<div class="row">
			<div class="col-md-10 col-md-offset-1 text-left">
				<div class="panel panel-default">
					<div class="panel-heading clearfix">
						<h3 class="panel-title lh-2">
							Payment {{Html::linkAction('PaymentController@index', 'Cancel', $status, array('class' => 'btn btn-danger dib btn-sm pull-right text-white'))}}
						</h3>
					</div>
					<div class="panel-body">
						<h5 class="mt-0">Project: {{ $registration['taskgroup']->name }}</h5>
						<h5 class="mt-0 mb-0">User: {{ $registration['profile']->name }} {{ $registration['profile']->surname }} ({{ $registration['user']->email }})</h5>
					</div>
				</div>
				@if ($registration['answers'])
				{!! BootForm::open(array('action' => array('PaymentController@update', $registration->id, $status ))) !!}
				<div class="panel panel-default mb-20">
					@foreach ($registration['answers'] as $answer)
					<div class="panel-heading clearfix">
						<h5 class="mt-0 mb-0 lh-16">Question: {{$answer['description']->question}}
							{!! BootForm::hidden('answer_status_id['.$answer["id"].']') !!}
							<span class="btn btn-info btn-sm pull-right text-white">Money: {{$answer['money']}}</span>
						</h5>
					</div>
					@endforeach
					<div class="panel-body">
						<h5 class="mt-0 mb-0 lh-16">Total:
							<span class="btn btn-info btn-sm pull-right text-white">Money: {{$registration->total_money}}</span>
						</h5>
					</div>
					<div class="panel-footer">
						{!! BootForm::select('status', 'Status', $statuses, $registration->answer_status, ['required' => true]) !!}
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-body">
						{!! BootForm::submit('Submit',  ['class' => 'btn btn-primary pull-right text-white pull-right' ]) !!}
					</div>
				</div>
				{{ BootForm::close() }}
				@else
				There are no answers
				@endif
			</div>
		</div>
	</div>
</div>
</div>
@endsection
@push('styles')
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/3.3.2/css/bootstrap2/bootstrap-switch.min.css" rel="stylesheet">
@endpush
@push('scripts')
<script src="//cdnjs.cloudflare.com/ajax/libs/geocomplete/1.7.0/jquery.geocomplete.min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key={!!env('GOOGLE_API_KEY') !!}&amp;libraries=places&amp;language=en-GB"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/3.3.2/js/bootstrap-switch.min.js"></script>
<script type="text/javascript">
$('.switch').bootstrapSwitch();
</script>
<script type="text/javascript">
$(':radio,:checkbox').click(function(){
	return false;
});
</script>
@endpush

resources/views/admin/payment/index.blade.php
@extends('layouts.app')

@section('content')
<div class="main-full-back text-center vcenter min-height-100pc pt-20">
	<div class="container">
		<div class="row mb-20">
			<div class="col-md-5 col-md-offset-1 text-left">
				<ul class="list-inline">
					<li>{!! Html::decode(Html::linkAction('PaymentController@index', 'all', null)) !!}</li>
					@foreach ($statuses as $statuses)
					<li>{!! Html::decode(Html::linkAction('PaymentController@index', $statuses->status, [$statuses->status])) !!}</li>
					@endforeach
				</ul>
			</div>

			<div class="col-md-5 text-right">
				@if ($status)
				<ul class="list-inline">
					<li>{!! Html::decode(Html::linkAction('PaymentController@index', 'Individual', [$status])) !!}</li>
					<li>{!! Html::decode(Html::linkAction('PaymentController@index', 'Grouped', [$status, 'grouped'])) !!}</li>
				</ul>
				@endif
			</div>
		</div>
		<div class="row">
			<div class="col-md-10 col-md-offset-1 text-left">
				<div class="panel panel-default">
					<div class="panel-heading clearfix">
						<h3 class="panel-title">Payment</h3>
					</div>
					<div class="panel-body">
						@if ($registrations->count())
						@if ($group && $status!='paid')
						{{ Form::open(array('method' => 'post','url' => array('admin/payment/bulk', $status))) }}
						@endif
						<table class="table table-striped table-condensed fs-13" id="datatable" style="width:100%;">
							<thead>
								<tr>
									<th>ID</th>
									<th>User</th>
									@if ($group)
									<th>IBAN</th>
									@else
									<th>Taskgroup</th>
									@endif
									<th>Money</th>
									@if ($group)
									<th>Bank</th>
									@endif
									<th>Status</th>
									@if ($status=='accepted')
									<th>Redeem</th>
									@endif
									@if ($status!='paid')
									<th>Actions</th>
									@endif
								</tr>
							</thead>
							<tbody>
								@foreach ($registrations as $registration)
								<tr>
									<td>{{ $registration->id }}</td>
									<td>{{ $registration->user['email'] }}</td>
									@if ($group)
									<td>{{ Helper::getUserProfile($registration->user_id)['IBAN'] }}</td>
									@else
									<td>{{ $registration->taskgroup['name'] }}</td>
									@endif
									<td>{{ $registration->answers_money }}</td>
									@if ($group)
									<td>{{ Helper::getBank(Helper::getUserProfile($registration->user_id)['bank_id']) }}</td>
									@endif
									<td>{{ $registration->answers_status }}</td>
									@if ($status=='accepted')
									<td>{{ $registration->redeem_status }}</td>
									@endif
									@if ($status!='paid')
									@if ($group)
									<td nowrap>
										{!! Form::checkbox('user_id[]', $registration->user_id, null, ['class'=> 'switch']) !!}
									</td>
									@else
									<td nowrap>
										{!! Html::decode(Html::linkAction('PaymentController@edit', '<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', [$registration->id, $status], array('class' => 'btn btn-info dib btn-sm'))) !!}
									</td>
									@endif
									@endif
								</tr>
								@endforeach
							</tbody>
							<tfoot>
								<tr>
									<td></td>
									<th>User</th>
									@if ($group)
									<th>Bank</th>
									@else
									<th>Taskgroup</th>
									@endif
									<td><input id="min" type="text" placeholder="Min" size="6"></br><input id="max" type="text" placeholder="Max" size="6"></td>
									@if ($group)
									<th>Bank</th>
									@endif
									<th>Status</th>
									@if ($status=='accepted')
									<th>Redeem</th>
									@endif
									@if ($status!='paid')
									<td></td>
									@endif
								</tr>
							</tfoot>
						</table>
						@if ($group && $status!='paid')
						<div class="panel-heading clearfix">
							{!! Form::button('Move Status', array('type'=>'submit','class' => 'btn btn-info btn-sm pull-right')) !!}
							{{ Form::close() }}
						</div>
						@endif
						@else
						There are no items to display
						@endif
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection
@push('styles')
<link href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="https://cdn.datatables.net/buttons/1.2.2/css/buttons.dataTables.min.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/3.3.2/css/bootstrap2/bootstrap-switch.min.css" rel="stylesheet">
@endpush
@push('scripts')
<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
<script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
<script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-daterangepicker/2.1.24/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-daterangepicker/2.1.24/daterangepicker.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/3.3.2/js/bootstrap-switch.min.js"></script>
<script type="text/javascript">
$.fn.dataTable.ext.search.push(
    function( settings, data, dataIndex ) {
        var min = parseFloat( $('#min').val(), 10 );
        var max = parseFloat( $('#max').val(), 10 );
        var age = parseFloat( data[3] ) || 0; // use data for the age column
 
        if ( ( isNaN( min ) && isNaN( max ) ) ||
             ( isNaN( min ) && age <= max ) ||
             ( min <= age   && isNaN( max ) ) ||
             ( min <= age   && age <= max ) )
        {
            return true;
        }
        return false;
    }
);
$(document).ready(function() {
    // Setup - add a text input to each footer cell
    $('#datatable tfoot th').each( function () {
    	var title = $(this).text();
    	$(this).html( '<input type="text" placeholder="Search '+title+'" size="10" id="fs"  />' );
    } );

    // DataTable
    var table = $('#datatable').DataTable({
    	dom: "<'row'<'col-sm-4'l><'col-sm-4'B><'col-sm-4'f>>" +
    	"<'row'<'col-sm-12'tr>>" +
    	"<'row'<'col-sm-5'i><'col-sm-7'p>>",
    	buttons: [
    	{
    		extend: "csv",
    		exportOptions: {
    			columns: [0, 1, 2, 3, 4, 5]
    		}
    	},
    	{
    		extend: "excel",
    		exportOptions: {
    			columns: [0, 1, 2, 3, 4, 5]
    		}
    	},
    	{
    		extend: "pdf",
    		exportOptions: {
    			columns: [0, 1, 2, 3, 4, 5]
    		}
    	},
    	{
    		extend: "print",
    		exportOptions: {
    			columns: [0, 1, 2, 3, 4, 5]
    		}
    	}
    	],
    	columnDefs: [{orderable: false, targets: -1 }],
    	order: [[ 0, "desc" ]],
    	stateSave: true
    });

    $('#min, #max').keyup( function() {
    	table.draw();
    } );
    // Apply the search
    table.columns().every( function () {
    	var that = this;

    	$( 'input#fs', this.footer() ).on( 'keyup change', function () {
    		if ( that.search() !== this.value ) {
    			that
    			.search( this.value )
    			.draw();
    		}
    	} );
    });

    // Date range script - Start of the sscript
    $("#date_start_range").daterangepicker({
    	autoUpdateInput: false,
    	locale: {
    		"cancelLabel": "Clear",
    	}
    });

    $("#date_start_range").on('apply.daterangepicker', function(ev, picker) {
    	$(this).val(picker.startDate.format('YYYY-MM-DD') + ' to ' + picker.endDate.format('YYYY-MM-DD'));
    	table.draw();
    });

    $("#date_start_range").on('cancel.daterangepicker', function(ev, picker) {
    	$(this).val('');
    	table.draw();
    });

});
$('.switch').bootstrapSwitch();
$('button.delete-btn').on('click', function(e){
	e.preventDefault();
	var self = $(this);
	swal({
		title             : "Are you sure?",
		text              : "You will not be able to recover this registration!",
		type              : "warning",
		showCancelButton  : true,
		confirmButtonColor: "#DD6B55",
		confirmButtonText : "Yes, delete it!",
		cancelButtonText  : "No, Cancel",
		closeOnConfirm    : false,
		closeOnCancel     : false
	},
	function(isConfirm){
		if(isConfirm){
			self.parents("#delete_form").submit();
		}
		else{
			swal("Cancelled","Your registration is safe", "error");
		}
	});
});
</script>
@endpush